import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Script from "next/script";

const uberMove = localFont({
  src: "../../public/font/UberMoveMedium.otf",
  variable: "--font-uber-move",
  display: "swap"
});

import Footer from "@/components/Footer";
import WhatsAppButton from "@/components/WhatsAppButton";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${uberMove.variable} font-sans antialiased`}
      >
        <Header />
        {children}
        
        <Footer />
        {/* <WhatsAppButton /> */}
        <script src="//code.tidio.co/bxpgyt5mdoulzj9kjkgbdghxc8vhntwm.js" async></script>
      </body>
    </html>
  );
}

